name: buzz_match
description: A platform that connects content creators with brands for advertising campaigns.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  timeline_tile: ^2.0.0
  flutter_localizations:
    sdk: flutter
  
  # State Management
  get: ^4.6.6
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.7.10
  
  # UI
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  lottie: ^2.7.0
  flutter_staggered_grid_view: ^0.7.0
  intl: ^0.19.0
  shimmer: ^3.0.0
  image_picker: ^1.0.7
  url_launcher: ^6.2.3
  flutter_native_splash: ^2.3.10
  
  # Authentication
  google_sign_in: ^6.1.6
  sign_in_with_apple: ^5.0.0
  
  # Payment
  stripe_payment: ^1.1.4
  flutter_paypal: ^0.2.0
  
  # Storage & Local DB
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Other
  connectivity_plus: ^5.0.2
  uuid: ^4.2.2
  path_provider: ^2.1.2
  permission_handler: ^11.1.0
  timeago: ^3.6.0
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^16.2.0
  photo_view: ^0.14.0
  signature: ^5.4.1
  pdf: ^3.10.7
  printing: ^5.11.1
  fl_chart: ^0.70.2
  multi_select_flutter: ^4.1.3
  file_picker: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
    - assets/animations/
    - .env
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700